index:
    path: /
    controller: App\Controller\indexController::show

games:
    path: /games
    controller: App\Controller\Games\GameController::show

game_promotion:
    path: /games/promotion-games
    controller: App\Controller\Games\PromotionController::show

game_free:
    path: /games/free-games
    controller: App\Controller\Games\FreeController::show

currency:
    path: /currency
    controller: App\Controller\Currency\CurrencyController::show
